#pragma once

enum ShellCommand {
    READ_COMMAND,
    WRITE_COMMAND,
    HELP_COMMAND,
    EXIT_COMMAND,
    FULLWRITE_COMMAND,
    FULLREAD_COMMAND,
    ERASE_COMMAND,
    ERASERANGE_COMMAND,
    FLUSH_COMMAND,
    SCRIPT_RUN_COMMAND
};
enum ShellScriptApiCommand { WRITE_SCRIPT_COMMAND, COMPARE_SCRIPT_COMMAND, SCRIPT_UNKOWN };
